### ISSUE TITLE
Update alt text

### ISSUE THREAD

**Issue by pletcher** [inscriptions-israel-palestine/iip-backend#10]
From Christine:

> There are occasional errors in the results page where instead of an image the page displays a copy of the title text in its place. See e.g. when you search for "Joseph". From a cursory look, this seems to be happening when the image link is broken -- I've clicked on a few and they lead to GitHub 404s.

**Comment by pletcher** [comment]
Should be fixed! cc @cmroughan

**Comment by cmroughan** [comment]
Yep, the updated alt text was a welcome change and looks to be working!

It's not a necessary tweak, but: if we could get any of the placeholders using the /img/iip_placeholder.png file to have the alt text "Image not yet available", that'd be a little more accurate.

**Comment by pletcher** [comment]
Updated the alt text again!
