### ISSUE TITLE
Make sure figures are ingested

### ISSUE THREAD

**Issue by pletcher** [inscriptions-israel-palestine/iip-backend#11]

**Comment by pletcher** [comment]
Should be fixed by https://github.com/inscriptions-israel-palestine/iip-backend/commit/30fa7ed95af4177916e3e5b0a18a149f2f673c14 -- @cmroughan, could you confirm?

**Comment by cmroughan** [comment]
Looks good -- searches on figures seem to be behaving as expected now

**Comment by pletcher** [comment]
Great, thank you!
