### ISSUE TITLE
Order cities in filter list

### ISSUE THREAD

**Issue by pletcher** [inscriptions-israel-palestine/iip-backend#3]
Fixed by https://github.com/pletcher/iip-backend/commit/1d91cf56d57edf38711a74669a3aa98d0445c9de#diff-dc95604971de3477f4ef2c3b3a6284a93654c6e4c5090ac619f4934412f8d40eR44

**Comment by pletcher** [comment]
@cmroughan, could you confirm that this is fixed when you get a chance?

**Comment by cmroughan** [comment]
Confirming that the alphabetic sort is working -- looks good! Any apparent duplicate entries are to be corrected in the underlying XML data. I'll make a note of that.

**Comment by pletcher** [comment]
Awesome, closing this one out, thanks!
