### ISSUE TITLE
Scrollable sidebar

### ISSUE THREAD

**Issue by pletcher** [inscriptions-israel-palestine/iip-backend#5]
Could we get a scrollbar on the search sidebar instead of having to scroll down the page as a whole when the accordion menus are opened? It's fine on the listed search results page, but on the map version I end up scrolling down past the map to just empty white page.

**Comment by pletcher** [comment]
Should be fixed! cc @cmroughan

**Comment by cmroughan** [comment]
Yep, looks great! And I'm not finding any bugs with it when transitioning between the map view and the list view, so that's looking good too.
