### ISSUE TITLE
Improve search logic

### ISSUE THREAD

**Issue by pletcher** [inscriptions-israel-palestine/iip-backend#6]
From Christine

> The search logic is behaving differently than a user might expect: I have selected [Physical Type = honorific or dedicatory] and also [Language = Greek]. Rather than returning Greek honorific or dedicatory inscriptions, it's returning honorific or dedicatory inscriptions in all languages, in addition to what seems to be every Greek inscription.

This should be fixed by https://github.com/pletcher/iip-backend/commit/d055de1f4b4ff39129bed605e03b5509a18d2dcd

**Comment by pletcher** [comment]
@cmroughan, could you review and confirm that this is fixed when you get a chance?

**Comment by cmroughan** [comment]
Confirming that the updated search logic is working to narrow down results when filtering by language

**Comment by pletcher** [comment]
Thanks!
