### ISSUE TITLE
Empty text searches returning 0 results

### ISSUE THREAD

**Issue by pletcher** [inscriptions-israel-palestine/iip-backend#7]
Should be fixed by https://github.com/pletcher/iip-backend/commit/d055de1f4b4ff39129bed605e03b5509a18d2dcd

**Comment by pletcher** [comment]
@cmroughan, could I get your confirmation that this is fixed?

**Comment by cmroughan** [comment]
Was it the empty text search that was causing issues when trying search by date? Can confirm that those searches are working now, even without a query input in the 'Text or translation' field.

**Comment by pletcher** [comment]
Yep, that's exactly what was happening -- thank you for catching this!
